#!/usr/bin/env python3
import re
import sys

def print_help():
    print("Usage: validate_commit_msg.py <commit_msg_file>")
    sys.exit(1)

def validate_message(msg_file: str):
    try:
        with open(msg_file, "r", encoding="utf-8") as f:
            lines = f.readlines()
    except Exception as e:
        print(f"Error reading commit message file: {e}")
        sys.exit(1)

    if not lines:
        print("Error: Commit message is empty.")
        sys.exit(1)

    subject = lines[0].strip()
    
    # Ignore merge commits or squash commits automatically generated by git
    if subject.startswith("Merge branch") or subject.startswith("Merge pull request") or subject.startswith("Revert "):
        print("Git system commit detected. Skipping verification.")
        sys.exit(0)

    errors = []

    # 1. Subject length check (standard <= 50, max limit 72)
    if len(subject) > 72:
        errors.append(f"Subject line is too long ({len(subject)} chars). Keep it under 72 (ideally 50).")

    # 2. Trailing period check
    if subject.endswith("."):
        errors.append("Do not end the subject line with a period.")

    # 3. Conventional Commit prefix syntax check
    conventional_pattern = r"^(feat|fix|docs|style|refactor|test|chore|perf|ci|build)(\([a-zA-Z0-9_-]+\))?:\s+.+$"
    if not re.match(conventional_pattern, subject):
        errors.append(
            "Subject line does not match Conventional Commit syntax.\n"
            "Format: <type>(<scope>): <subject>\n"
            "Examples:\n"
            "  - feat(auth): add google sign-in\n"
            "  - fix(billing): resolve stripe webhook issue\n"
            "  - docs: update setup manual"
        )

    # 4. Check for blank line between subject and body
    if len(lines) > 1:
        second_line = lines[1].strip()
        if second_line != "":
            errors.append("Subject line and body must be separated by a blank line.")

    if errors:
        print("\nInvalid Commit Message:")
        for err in errors:
            print(f" - {err}")
        print("\nCommit REJECTED. Please correct your message.")
        sys.exit(1)
    else:
        print("Success: Commit message complies with standards.")
        sys.exit(0)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print_help()
    validate_message(sys.argv[1])
